### PR TITLE
Fixed a licence conflict

### PR DESCRIPTION
**Pull request by sabianroberts**

### CODE REVIEW

**Comment by cobaltgit** [comment]
Just done it now, if somebody is willing to close this

**Comment by Rexogamer** [comment]
unless you somehow mange to fix everything before PRs get made you realise you can just merge them

**Comment by sabianroberts** [comment]
> Just done it now, if somebody is willing to close this

why didn't you ***merge the pull request***

**Comment by cobaltgit** [comment]
Conflicts mate

**Comment by Rexogamer** [comment]
conflicts... you made

**Comment by Rexogamer** [comment]
or rather, conflicts that could've easily been solved

**Pull request closed without merging**
